// Generated by CoffeeScript 1.6.2
(function() {
  var express;

  require('source-map-support').install();

  express = require('express');

  express().use(express["static"](__dirname)).listen(zzz);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
